### ISSUE TITLE
KeyError: 'unlimited'

### ISSUE THREAD

**Issue by Norien** [robmathers/rogersusage#4]
Version - 2.0.3

running a metered account and getting ```KeyError: 'unlimited'``` when running script

traceback:

```
Traceback (most recent call last):
  File "/home/homeassistant/.homeassistant/python_scripts/rogersusage.py", line 249, in <module>
    main()
  File "/home/homeassistant/.homeassistant/python_scripts/rogersusage.py", line 220, in main
    if not usage['unlimited']:
KeyError: 'unlimited'
```

I rolled back to version ```2.0.1``` and then added the workaround for login in ```2.0.3``` and I'm back up and running.

**Comment by robmathers** [comment]
Thanks to @jumpkick, this should be fixed. Post if you run into any issues.

**Comment by deftdawg** [comment]
@robmathers no worries... came across your code while looking for a python lib I could use to make a home-assistant component to better track household internet usage before it gets to 75% (I'm not on the unlimited plan).

**Comment by Norien** [comment]
@jumpkick thats why i'm here as well here is my example yaml

```
  - platform: command_line
    command: "python /home/homeassistant/.homeassistant/python_scripts/rogersusage.py --l=email@wahtever.com --p=passwprd --csv"
    name: 'usage'
    scan_interval: 21600
  - platform: template
    sensors:
      usage_downloaded:
        value_template: "{{states.sensor.usage.state.split(',')[0]}}"
        unit_of_measurement: "GB"
      usage_uploaded:
        value_template: "{{states.sensor.usage.state.split(',')[1]}}"
        unit_of_measurement: "GB"
      usage_total_usage:
        value_template: "{{states.sensor.usage.state.split(',')[2]}}"
        unit_of_measurement: "GB"
       usage_usage_cap:
         value_template: "{{states.sensor.usage.state.split(',')[3]}}"
         unit_of_measurement: "GB"
       usage_remaining_usage:
         value_template: "{{states.sensor.usage.state.split(',')[4]}}"
         unit_of_measurement: "GB"
```

**Comment by deftdawg** [comment]
@Norien nice, I took yours and added some friendly names and hid the raw value...  one thing still needed though is the remaining days in the billing cycle, so I'll have to look at that.

```
  - platform: command_line
    command: "python ~/source/rogersusage/rogersusage.py --l=email@email.com --p=rogerspassword --csv"
    hidden: true
    name: 'usage'
    scan_interval: 21600
  - platform: template
    sensors:
      usage_downloaded:
        friendly_name: "Rogers Usage: Downloaded"
        value_template: "{{states.sensor.usage.state.split(',')[0]}}"
        unit_of_measurement: "GB"
      usage_uploaded:
        friendly_name: "Rogers Usage: Uploaded"
        value_template: "{{states.sensor.usage.state.split(',')[1]}}"
        unit_of_measurement: "GB"
      usage_total_usage:
        friendly_name: "Rogers Usage: Total Bandwidth"
        value_template: "{{states.sensor.usage.state.split(',')[2]}}"
        unit_of_measurement: "GB"
      usage_usage_cap:
        friendly_name: "Rogers Usage: Cap"
        value_template: "{{states.sensor.usage.state.split(',')[3]}}"
        unit_of_measurement: "GB"
      usage_remaining_usage:
        friendly_name: "Rogers Usage: Remaining Bandwidth"
        value_template: "{{states.sensor.usage.state.split(',')[4]}}"
        unit_of_measurement: "GB"

```
